### ISSUE TITLE
Confusing org/package name

### ISSUE THREAD

**Issue by theodorejb** [litesaml/lightsaml#14]
Why is the organization named "litesaml", but the repository/package is still named "lightsaml"? This is very confusing.

**Comment by william-suppo** [comment]
Hi @theodorejb,

The code base dont change between `v2.3.4` of `lightsaml/lightsaml` package & `v3.0.0` of `litesaml/lightsaml`.

I focus on Organisation because I want to update Lightsaml ecosystem like [this new documentation](https://litesaml.github.io/) who's I'm writing.

 I want to cause the least amount of work for the communit, so I preserve the core package `lightsaml`.

Ciao
